apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
  namespace: default
  labels:
    name: nfs-pod
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    name: nfs-ctn
    volumeMounts:
      - name: nfsvol
        mountPath: /tmp
  restartPolicy: Always
  securityContext:
    fsGroup: 65534
    runAsUser: 65534
  volumes:
    - name: nfsvol
      persistentVolumeClaim:
        claimName: nfs-pvc